### ISSUE TITLE
проверить, что массив отсортирован

### ISSUE THREAD

**Issue by JFixby** [borovelli/Javavelli#2]
напиши функцию которая принимает массив int[] и возвращает true если он отсортирован
и false если нет
напиши пару тестов для неё

**Comment by borovelli** [comment]
zaebalsya, ne rabotaet 1 iz funkzii: perevod list to Array
otpisalsya tebe v VK. https://github.com/borovelli/Javavelli/blob/master/borovelli-javavelli/src/com/github/borovelli/javavelli/sorting/IntCheckSorting.java

**Comment by JFixby** [comment]
http://stackoverflow.com/questions/3293946/the-easiest-way-to-transform-collection-to-array

**Comment by JFixby** [comment]
сделай pull, я добавил тебе тестов: https://github.com/borovelli/Javavelli/blob/master/borovelli-javavelli/src/com/github/borovelli/javavelli/sorting/IsSorted.java#L17

**Comment by JFixby** [comment]
можешь теперь вызывать`IsSorted.isSorted()` из других классов
